"""Add full_name to secure_identities

Revision ID: 4bb484424e1f
Revises: bbaaf3beeb7a
Create Date: 2025-12-25 15:20:46.417960

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bb484424e1f'
down_revision = 'bbaaf3beeb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secure_identities', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('secure_identities', sa.Column('blind_index_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('secure_identities', sa.Column('encrypted_data_blob', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('secure_identities', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_secure_identities_blind_index'), table_name='secure_identities')
    op.create_index(op.f('ix_secure_identities_blind_index_hash'), 'secure_identities', ['blind_index_hash'], unique=True)
    op.drop_column('secure_identities', 'encrypted_blob')
    op.drop_column('secure_identities', 'blind_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secure_identities', sa.Column('blind_index', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('secure_identities', sa.Column('encrypted_blob', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_secure_identities_blind_index_hash'), table_name='secure_identities')
    op.create_index(op.f('ix_secure_identities_blind_index'), 'secure_identities', ['blind_index'], unique=True)
    op.drop_column('secure_identities', 'created_at')
    op.drop_column('secure_identities', 'encrypted_data_blob')
    op.drop_column('secure_identities', 'blind_index_hash')
    op.drop_column('secure_identities', 'full_name')
    # ### end Alembic commands ###
