"""Add table secure_identities

Revision ID: bbaaf3beeb7a
Revises: 1a31ce608336
Create Date: 2025-12-24 15:58:41.446639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbaaf3beeb7a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secure_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_blob', sa.LargeBinary(), nullable=False),
    sa.Column('blind_index', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secure_identities_blind_index'), 'secure_identities', ['blind_index'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secure_identities_blind_index'), table_name='secure_identities')
    op.drop_table('secure_identities')
    # ### end Alembic commands ###
